[package]
name = "cli"
version = "0.1.0"
authors = ["Fchen"]
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.216", features = ["derive"] }
